version: '3.8'

services:
  victim:
    build: ./victim
    container_name: lab_victim
    networks:
      lab_net:
        ipv4_address: 10.0.0.5

  detector:
    build: ./detector
    container_name: lab_detector
    network_mode: "service:victim"
    depends_on:
      - victim
    volumes:
      - alert_logs:/app/logs

  attacker:
    build: ./attacker
    container_name: lab_attacker
    networks:
      lab_net:
        ipv4_address: 10.0.0.10
    stdin_open: true 
    tty: true

  dashboard:
    build: ./dashboard
    container_name: lab_dashboard
    ports:
      - "8080:80"
    networks:
      lab_net:
        ipv4_address: 10.0.0.15
    volumes:
      - alert_logs:/usr/share/nginx/html/logs

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

volumes:
  alert_logs:
